### ISSUE TITLE
support convert to markdown style table

### ISSUE THREAD

**Issue by heartacker** [Plasma/csv-to-table#10]
thanks.
that will be great if we could convert tsv.csv.. to markdown table so that  we could edit markdown table more easy

**Comment by Plasma** [comment]
Hey there,

Thanks for the suggestion. If I understand correctly, you want to take a CSV output like this:

```
Name,Age
Jake,30
Lisa,36
```

And convert that to Markdown table format:

```
| Name | Age |
| ---- | --- |
| Jake | 30  |
| Lisa | 36  |
```

Instead of the current "ASCII" format:

```
|------|-----|
| Name | Age |
|------|-----|
| Jake | 30  |
|------|-----|
| Lisa | 36  |
|------|-----|
```

I could make this an option you choose in settings, would that be good?

**Comment by heartacker** [comment]
> Hey there,
> 
> Thanks for the suggestion. If I understand correctly, you want to take a CSV output like this:
> 
> ```
> Name,Age
> Jake,30
> Lisa,36
> ```
> 
> And convert that to Markdown table format:
> 
> ```
> | Name | Age |
> | ---- | --- |
> | Jake | 30  |
> | Lisa | 36  |
> ```
> 
> Instead of the current "ASCII" format:
> 
> ```
> |------|-----|
> | Name | Age |
> |------|-----|
> | Jake | 30  |
> |------|-----|
> | Lisa | 36  |
> |------|-----|
> ```
> 
> I could make this an option you choose in settings, would that be good?
> 
> 

great thks

**Comment by Plasma** [comment]
Done! Please update to version `1.3.0` and you will find a new option in extension settings to enable markdown output support.
