### ISSUE TITLE
Need copyright or license

### ISSUE THREAD

**Issue by rlgloden** [Plasma/csv-to-table#16]
I'm almost embarrassed to ask ... but my company needs a copyright or license in the source files before they authorize us to use open source tools like your vscode csv-to-table.  Just a simple but standard copyright or license statement in the source files would help me get your tool through our vetting process.  Thanks in advanced.

**Comment by Plasma** [comment]
No problem, thanks for your interest in the extension, I've added the MIT License file to the project.
