### ISSUE TITLE
Support markdown preview

### ISSUE THREAD

**Issue by ThePlenkov** [Plasma/csv-to-table#17]
Hi! I would like to suggest you to generate CSV table in the way that it could be possible to view this generated file in markdown format. Currently is like this:
![image](https://user-images.githubusercontent.com/6381507/172336742-00216b3f-20e3-4dc3-a662-0485cd7c6cfb.png)
Do you think is possible?

Thanks!

**Comment by Plasma** [comment]
Hi @ThePlenkov , yes! This is already a feature, its hidden away under extension settings, turn on `Write the generated table using Markdown format instead of the default style`.
