### ISSUE TITLE
Configurable delimiter

### ISSUE THREAD

**Issue by contentfree** [Plasma/csv-to-table#2]
It would be nice to be able to have an option that asks for the delimiter string. Then I'd be able to break up strings with double percent signs as separators, for example.

Thanks for the extension!

**Comment by Plasma** [comment]
Hi @contentfree ,

This is an option as part of the command pallet, try using the `Convert to table from a custom defined separator` command.

**Comment by contentfree** [comment]
Will do. Sorry that I must've missed that.
