### ISSUE TITLE
How do I set the separator to a tab instead of a comma?

### ISSUE THREAD

**Issue by joonykims** [Plasma/csv-to-table#20]
When I tried to use the results of the DB query, I found that many commas were used in the query, so they were not suitable as separators. How can I handle this when a tab delimiter is selected?

**Comment by joonykims** [comment]
Ah...I'm sorry...I found a way...
I found that it has TSV functionality.
I asked too urgently.
Thank you for developing a great tool.

**Comment by Plasma** [comment]
Thanks for the kind words, there’s also a custom delimiter option too if that is ever needed.
