### ISSUE TITLE
cant even add separator option?

### ISSUE THREAD

**Issue by abdullzz** [Plasma/csv-to-table#5]
hello bro. do u know that csv has various separator? thanks

**Comment by Plasma** [comment]
Hi @abdullzz 

Yes, the extension supports any separator:

* Convert to table from CSV (.csv / commas)
* Convert to table from TSV (.tsv / tabs)
* Convert to table from PSV (.psv / pipes)
* Convert to table from SSV (.ssv / semicolon)
* Convert to table from a custom defined separator <--- This one lets you enter any character

Perhaps try using the last menu option?
